name: grad_ready
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  flutter_svg: ^2.0.10
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# --- ضيفي الجزء ده هنا ---
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  # ملحوظة: لو اللوجو SVG، المكتبة هتحاول تحوله، 
  # لو واجهتي مشكلة يفضل تحويله لـ PNG بمقاس 1024x1024
# -----------------------

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg  # عشان نستخدمه جوه الأبلكيشن
    - assets/logo.png  # عشان نستخدمه للأيقونة الخارجية (Launcher Icon)