name: grad_ready
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  
  # مكتبات فيربيز (Firebase) - تم توحيد النسخ ومنع التكرار
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.0

  # مكتبات التصميم والأيقونات
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  # تم تعديل النسخة لمتوافقة مع الـ SDK
  flutter_launcher_icons: ^0.14.1

# إعدادات أيقونة التطبيق
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.svg
    - assets/logo.png